### ISSUE TITLE
Loading data

### ISSUE THREAD

**Issue by amuse38** [michaeltandy/contraction-hierarchies#2]
Hi,

Many thanks for your wonderful work.
Have you any sample code related to the loading process (I guess you used PBF file) ?
I'm particularly interested in discovering how handling AccessOnly and TurnRestriction.

Many thanks in advance for your help,

Best regards,

Alain

**Comment by michaeltandy** [comment]
I decided not to put PBF file reading into the contraction hierarchies
library itself, so it can be used with different sources of map data
without needing things like protobuf in order to build.

My PBF handling code is poorly maintained and not a good example of
competent engineering - but it's available anyway:
https://github.com/michaeltandy/OSM-binary/blob/planet-processing/src.java/uk/me/mjt/osmpbf/planetproc/ProcessPlanet.java


Understandably, people who input data for OpenStreetMap mostly focus on
things that can be input with the normal editors, with effects that can be
seen in normal viewers. So simple turn restrictions like 'No turn from A to
B' are mostly OK. Unfortunately for more complex restrictions (no turn from
A via B to C) there isn't much support among editors or routing engines -
so the map data can be a bit inconsistent.

Could I ask what you're working on? If you're planning to implement this
stuff yourself I might be able to give you a few pointers.

**Comment by amuse38** [comment]
Hi Michael, 

Many thanks for your answer ! 
We are trying to develop lightweight embedded map for mobile phone integrating some routing index. 
Due to the restrictions of the device, we would like to preprocess the data to be as efficient as possible. 
We are, of course, very interested in any clues or advices, pointers, ... ! 

Once again, many thanks for your precious help, and congratulations for your great job and blog ! 

Best regards, 

Alain 

----- Mail original -----

De: "Michael Tandy" <notifications@github.com> 
À: "michaeltandy/contraction-hierarchies" <contraction-hierarchies@noreply.github.com> 
Cc: "Alain MUSE" <alain.muse@laposte.net> 
Envoyé: Mardi 19 Janvier 2016 13:45:27 
Objet: Re: [contraction-hierarchies] Loading data (#2) 

I decided not to put PBF file reading into the contraction hierarchies 
library itself, so it can be used with different sources of map data 
without needing things like protobuf in order to build. 

My PBF handling code is poorly maintained and not a good example of 
competent engineering - but it's available anyway: 
https://github.com/michaeltandy/OSM-binary/blob/planet-processing/src.java/uk/me/mjt/osmpbf/planetproc/ProcessPlanet.java 


Understandably, people who input data for OpenStreetMap mostly focus on 
things that can be input with the normal editors, with effects that can be 
seen in normal viewers. So simple turn restrictions like 'No turn from A to 
B' are mostly OK. Unfortunately for more complex restrictions (no turn from 
A via B to C) there isn't much support among editors or routing engines - 
so the map data can be a bit inconsistent. 

Could I ask what you're working on? If you're planning to implement this 
stuff yourself I might be able to give you a few pointers.

**Comment by michaeltandy** [comment]
My project is intended for server applications where I can hold everything in memory to get good response times; for the UK I need about 16gb of RAM (I haven't heavily optimised my RAM use but I've tried to keep it somewhat controlled) and my turn restriction code isn't finished. So, you'll want to be more efficient than me :)

The OpenStreetMap data is a bit variable - a lot of it is good quality, but there are a lot of outliers too. For example [roads reported as non-private but that can only be reached by private roads](https://www.openstreetmap.org/way/218923344) and [barriers reported at T-junctions](https://www.openstreetmap.org/node/25417796). Simple turn restrictions are consistent enough - but there doesn't seem to be much consensus on how to tag [junctions like this one](http://www.openstreetmap.org/node/1675447389) where you're allowed to enter from the north and go from adelphi st via crescent to oldfield road, but you're not allowed to enter from the west and go from crescent to oldfield road.

In order to support turn restrictions properly you'll also need to support U-turn penalties even for junctions that don't have anything special about them - the reason is [junctions like this one](https://www.openstreetmap.org/node/237900) where you can go from-south-to-west but not from-north-to-west. If you don't have a U-turn penalty, the shortest path is to go north to south, then u-turn, then go south to west. Technically legal, but not something any real driver would do.

The approach I've been taking for turn restrictions is: I replace node-as-a-physical-location with node-as-a-combination-of-physical-location-and-state. So instead of being just "at node 237900" you are "at node 237900 having arrived from way 73058401 and with turn restriction 5601987 active" - and the state info allows me to figure out which node-states we're permitted to reach from the current one. The node-states form a graph just like the roads and junctions do. Unfortunately this method means you end up with a bunch of nodes - several per physical junction. When I get around to finishing my support I'm expecting to need even more RAM :-s

I wasn't able to find any literature describing how other people have approached this problem, so I'm not sure if my solution is really the best one. Let me know if you hear of a better way of doing it!

I also recommend you have lots of small, fast-to-run unit tests - [here are some of mine](https://github.com/michaeltandy/contraction-hierarchies/blob/4d19461c175743ad142bd3753913e05912e6478f/src/test/java/uk/me/mjt/ch/AdjustGraphForRestrictionsTest.java) - and add to them every time you find your code producing the wrong results.

**Comment by amuse38** [comment]
Hi Michael, 

Many thanks for this detailed answer. 
We got the same conclusion as you: handling everything in RAM provides better result than using a DB even on an SSD. 
We are going to finish our loader before contracting the graph but for sure, we will integrate those precious feedbacks in our approach. 

And you're right, documentation is really poor on this topic. Had you a look to OSM2PO ? 
Even if the code is not publicly available, the tool is quite interesting even if it provides some strange results for pedestrian. 

Anyway, many thanks for your precious help ! 

Best regards, 

Alain 

----- Mail original -----

De: "Michael Tandy" <notifications@github.com> 
À: "michaeltandy/contraction-hierarchies" <contraction-hierarchies@noreply.github.com> 
Cc: "Alain MUSE" <alain.muse@laposte.net> 
Envoyé: Samedi 23 Janvier 2016 13:31:59 
Objet: Re: [contraction-hierarchies] Loading data (#2) 



My project is intended for server applications where I can hold everything in memory to get good response times; for the UK I need about 16gb of RAM (I haven't heavily optimised my RAM use but I've tried to keep it somewhat controlled) and my turn restriction code isn't finished. So, you'll want to be more efficient than me :) 

The OpenStreetMap data is a bit variable - a lot of it is good quality, but there are a lot of outliers too. For example roads reported as non-private but that can only be reached by private roads and barriers reported at T-junctions . Simple turn restrictions are consistent enough - but there doesn't seem to be much consensus on how to tag junctions like this one where you're allowed to enter from the north and go from adelphi st via crescent to oldfield road, but you're not allowed to enter from the west and go from crescent to oldfield road. 

In order to support turn restrictions properly you'll also need to support U-turn penalties even for junctions that don't have anything special about them - the reason is junctions like this one where you can go from-south-to-west but not from-north-to-west. If you don't have a U-turn penalty, the shortest path is to go north to south, then u-turn, then go south to west. Technically legal, but not something any real driver would do. 

The approach I've been taking for turn restrictions is: I replace node-as-a-physical-location with node-as-a-combination-of-physical-location-and-state. So instead of being just "at node 237900" you are "at node 237900 having arrived from way 73058401 and with turn restriction 5601987 active" - and the state info allows me to figure out which node-states we're permitted to reach from the current one. The node-states form a graph just like the roads and junctions do. Unfortunately this method means you end up with a bunch of nodes - several per physical junction. When I get around to finishing my support I'm expecting to need even more RAM :-s 

I wasn't able to find any literature describing how other people have approached this problem, so I'm not sure if my solution is really the best one. Let me know if you hear of a better way of doing it! 

I also recommend you have lots of small, fast-to-run unit tests - here are some of mine - and add to them every time you find your code producing the wrong results.

**Comment by michaeltandy** [comment]
I've never looked at OSM2PO at all, sorry.
